// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDccoNtNF505JPwbyV2Oi4vXH4irzSnE',
    appId: '1:923793178616:web:d101ab282374d7b553e00d',
    messagingSenderId: '923793178616',
    projectId: 'veicabaste',
    authDomain: 'veicabaste.firebaseapp.com',
    storageBucket: 'veicabaste.firebasestorage.app',
    measurementId: 'G-VD3X0W8FRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYl4LahRhY9FeuGfyQW84z5mToN7_6Be4',
    appId: '1:923793178616:android:9e7bc2af59f9984c53e00d',
    messagingSenderId: '923793178616',
    projectId: 'veicabaste',
    storageBucket: 'veicabaste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYXX3Hxvf7M10Ssev8x_KnRdvsJVKUyY',
    appId: '1:923793178616:ios:6e63efbb2f53df5d53e00d',
    messagingSenderId: '923793178616',
    projectId: 'veicabaste',
    storageBucket: 'veicabaste.firebasestorage.app',
    iosBundleId: 'com.example.abastVeiculo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYXX3Hxvf7M10Ssev8x_KnRdvsJVKUyY',
    appId: '1:923793178616:ios:6e63efbb2f53df5d53e00d',
    messagingSenderId: '923793178616',
    projectId: 'veicabaste',
    storageBucket: 'veicabaste.firebasestorage.app',
    iosBundleId: 'com.example.abastVeiculo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrDccoNtNF505JPwbyV2Oi4vXH4irzSnE',
    appId: '1:923793178616:web:2d6a46f87aba339653e00d',
    messagingSenderId: '923793178616',
    projectId: 'veicabaste',
    authDomain: 'veicabaste.firebaseapp.com',
    storageBucket: 'veicabaste.firebasestorage.app',
    measurementId: 'G-XMX0REKXDS',
  );
}
